language: node_js
node_js:
  - node
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_module
notifications:
  email: false
install: yarn 
script: yarn test && yarn build
after_success:
  - yarn report-coverage
deploy:
  provider: script
  skip_cleanup: true
  script: yarn semantic-release & yarn deploy-storybook -- --ci
